name: Release Action

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    steps:
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        generateReleaseNotes: true
        bodyFile: "releaseBody.md"