name: Release Action

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: ".github/workflows/releaseBody.md"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
