name: Release Action

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Make
      id: release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        generateReleaseNotes: true
    - name: Date
      id: date
      run: echo "::set-output name=date::$(date +'%b %d, %Y, %I:%M %p UTC')"
    - name: Edit
      uses: irongut/EditRelease@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ steps.release.outputs.id }}
        body: '
          ---

          ## Testing Details:
          
          * Basic [Whiteglove](https://www.notion.so/playcoinc/Test-Plan-15457d2a923f4f47ae7045b9643665cf)

          ## Release Info

          **Release Owner**: @${{ github.actor }}

          **Release Type / Risks**: Hotfix / Minor (_PO / Manager sign-off_) / Major (_Customer Support / PO / Manager sign-off_)

          ## Sign-off

          **Approvals**:

          **Rollout Date**: ${{ steps.date.outputs.date }}'
