name: Release Action

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Make
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
        generateReleaseNotes: true
    - name: Get Release
      id: release
      uses: KevinRohn/github-full-release-data@v2.0.0
